Umair dev
eLearningDAO/POCRE pull request #326
Opened 2023-03-01 17:53 UTC by UmairMukhtar

Issue Fixed 
https://github.com/eLearningDAO/POCRE/issues/292

2023-03-01 18:51 UTC, UmairMukhtar commented
[Video_2023_03_01-4.webm](https://user-images.githubusercontent.com/34018917/222223715-0a10ec50-c508-497e-8b6d-cd2bfac2a5b4.webm)

2023-03-01 19:30 UTC, AltiMario requested changes
It doesn't work for me
![image](https://user-images.githubusercontent.com/598726/222244643-673ff319-b837-453b-abdc-3b0b5412585b.png)

2023-03-02 05:44 UTC, UmairMukhtar commented on app/api/src/utils/getSupportedFileTypeFromLink.ts
> +  })
have you tried it locally?

2023-03-02 05:46 UTC, UmairMukhtar commented
@AltiMario i have tried with a link similar to your link and it worked for me please have a look

[Link Similar to Mario.webm](https://user-images.githubusercontent.com/34018917/222341897-d607435e-73cc-4e16-adc3-d050744d2ead.webm)

2023-03-02 10:48 UTC, AltiMario approved these changes
I cannot test properly because there is a backend component not published

2023-03-03 20:44 UTC, UmairMukhtar commented on app/web-frontend/src/pages/Creations/common/form/Steps/Two.jsx
> -
added again

2023-03-03 20:44 UTC, UmairMukhtar commented on app/web-frontend/src/pages/Creations/common/form/Steps/Two.jsx
> -
added again

2023-03-03 20:44 UTC, UmairMukhtar commented on app/web-frontend/src/pages/Creations/common/form/Steps/Two.jsx
> -              {isValidatingLink ? <Loader /> : 'Update File'}
added again

2023-03-03 20:44 UTC, UmairMukhtar commented on app/web-frontend/src/pages/Creations/common/form/Steps/One.jsx
> -  const { linkError, validateLink, isValidatingLink } = useLinkValidation({ customErrorMessage: 'Invalid creation source link' });
added again

2023-03-03 20:45 UTC, UmairMukhtar commented on app/api/src/utils/getSupportedFileTypeFromLink.ts
> +var http = require('http');
fixed

2023-03-04 15:31 UTC, UmairMukhtar commented
![image](https://user-images.githubusercontent.com/34018917/222914762-0ec385f7-cea3-48f2-81ce-d179bf8b874c.png)

2023-03-04 15:59 UTC, AltiMario approved these changes

2023-03-05 10:08 UTC, AltiMario commented
good point

2023-03-05 13:22 UTC, UmairMukhtar commented
Creation Details Page
![image](https://user-images.githubusercontent.com/34018917/222963093-70e4e991-eeac-45da-9f67-77efd1408360.png)

2023-03-05 13:52 UTC, UmairMukhtar commented
Home Screen
![image](https://user-images.githubusercontent.com/34018917/222964555-41b513c2-0d5c-41e1-8a96-b91930aa1dfd.png)

2023-03-05 14:12 UTC, UmairMukhtar commented
![image](https://user-images.githubusercontent.com/34018917/222965738-00a67e41-c47b-48fb-88be-945316218825.png)

2023-03-05 14:13 UTC, UmairMukhtar commented
![image](https://user-images.githubusercontent.com/34018917/222965767-ddbf99b2-3d32-447f-bf12-938153accd41.png)

2023-03-05 20:38 UTC, UmairMukhtar commented
![image](https://user-images.githubusercontent.com/34018917/222984594-6a1d1497-9d28-43a3-97dc-92570f80ad3b.png)

2023-03-06 09:57 UTC, merged