avoid refresh due to cash issue fixed
eLearningDAO/POCRE pull request #341
Opened 2023-03-19 12:35 UTC by UmairMukhtar

[avoid refresh(1).webm](https://user-images.githubusercontent.com/34018917/226175520-652ee6d0-3558-4be8-bdf2-66f1838559da.webm)

2023-03-20 00:03 UTC, AltiMario requested changes
I tested switching between 2 wallets and It doesn't work for me. I see creations associated to other users, I have to refresh the page to remove the "cache".

2023-03-20 00:06 UTC, UmairMukhtar commented
Yes i also noticed that , the non draft creations of previous login continue to display , i am looking into it

2023-03-20 17:32 UTC, UmairMukhtar commented
[Creations loading without refresh.webm](https://user-images.githubusercontent.com/34018917/226420960-075d7276-3f51-4438-b612-ff386b4175d0.webm)


@AltiMario correct creation are now being loaded without refresh

2023-03-20 22:45 UTC, AltiMario approved these changes

2023-03-23 17:57 UTC, UmairMukhtar commented
Creations of separate route for public creations leads to these desirable results
[Other user creation , multiple wallet creations fixed.webm](https://user-images.githubusercontent.com/34018917/227301762-f215764e-6f17-45b1-9aff-acc832093a0c.webm)

2023-03-25 07:46 UTC, UmairMukhtar commented
[Multiple Wallet and Multiple user Creations.webm](https://user-images.githubusercontent.com/34018917/227704484-52d3b1d9-39d1-479e-b647-b32daeb49a6d.webm)

2023-03-25 07:55 UTC, UmairMukhtar commented
[Results from Deploy Preview.webm](https://user-images.githubusercontent.com/34018917/227704843-99156cbd-4a36-4d7a-96f0-2a1c98bd0749.webm)


Deploy Preview

2023-03-25 09:53 UTC, AltiMario approved these changes
looks good to me :-)

2023-03-25 09:59 UTC, UmairMukhtar commented on app/web-frontend/src/pages/Creations/Home/useCreations.jsx
> +  const cookieUser = Cookies.get('authUser');
authHelper was not working

2023-03-25 10:06 UTC, UmairMukhtar commented on app/web-frontend/src/pages/Creations/Home/useCreations.jsx
> +    enabled: !!user,
Done

2023-03-25 10:06 UTC, UmairMukhtar commented on app/web-frontend/src/pages/Wallet/common/components/profile.jsx
> +      setTimeout(() => {
Yes , because the new queries are called instantly so i added delay in the refresh cache

2023-03-25 10:08 UTC, UmairMukhtar commented
![image](https://user-images.githubusercontent.com/34018917/227710810-e13cf6c4-39c6-4cd5-8a5a-b5b1bc2f196c.png)

2023-03-25 11:43 UTC, UmairMukhtar commented on app/web-frontend/src/pages/Wallet/common/components/profile.jsx
> +      setTimeout(() => {
done

2023-03-25 11:44 UTC, UmairMukhtar commented on app/web-frontend/src/pages/Creations/Home/useCreations.jsx
> +  const cookieUser = Cookies.get('authUser');
done thanks

2023-03-25 14:17 UTC, merged